### ISSUE TITLE
[bug] Cannot execute WarpScripts

### ISSUE THREAD

**Issue by miton18** [senx/VSCode-WarpScriptLanguage#25]
I have a file, his content is: 

```
1 1  +
```

When I run the WarpScript:

```
[3:18:57 PM] ERROR /Users/miton18/Desktop/test.mc2:1 in section '[TOP]': Unknown function '3T0TÐPÀæ'
```

VsCode version: 1.27.0-insider

**Comment by Giwi** [comment]
Hi, I can't reproduce on the latest stable version of VSCode: 1.26.1

Could you try a stable version?

**Comment by aurrelhebert** [comment]
Hi, I got the same issue with Version 1.22.2 and 1.26.1, executing the WarpScript with a cURL command on the same file works fine

**Comment by Giwi** [comment]
Strange.. on which OS?

**Comment by Giwi** [comment]
What is your value of the "files.encoding" VSCode pref?

**Comment by aurrelhebert** [comment]
Ubuntu 16.04.4 LTS, and default one "files.encoding": "utf8"

**Comment by Giwi** [comment]
Does your Warp 10 server accepts Gzip?

**Comment by aurrelhebert** [comment]
True, it doesn't accept Gzip

**Comment by Giwi** [comment]
The requester of this plugin uses Gzip as default because Warp 10 accepts Gzip by default.

**Comment by miton18** [comment]
We are adding Gzip support on request on all protocols :-)

**Comment by Giwi** [comment]
Nice :) With WarpScripts which return huge JSON, you will enjoy it ;)
