### ISSUE TITLE
Integrate a preference toggle to desactivate the automatic GTS preview

### ISSUE THREAD

**Issue by ghost** [senx/VSCode-WarpScriptLanguage#35]
When I execute a warpscript in VSCode, I get the result (state of the stack) in a tab AND the GTS Preview in another tab with the focus on it. But...

... I don't want GTS preview, it's pointless for me, very annoying, and I have no clue how to not trigger it.

Please add en option to preview only on demand.

**Comment by Giwi** [comment]
done in 1.0.0 ;)

**Comment by ghost** [comment]
Thx so much!

**Comment by Giwi** [comment]
You are welcome :)
