### ISSUE TITLE
Unable to write when the extension is enable

### ISSUE THREAD

**Issue by vballu** [senx/VSCode-WarpScriptLanguage#40]
Hello,

Since I updated vscode to the version 1.47, when the warpscript extension is enabled, I am unable to write except for deleting characters by the `suppr` key when the warpscript extension is enabled.

**Comment by Giwi** [comment]
Strange, I just tested it with the same version and everything works well.
Which OS do you use and which are the other VSCode extensions?

**Comment by pi-r-p** [comment]
Hello,
No problem here. Please try do de-activate all your extensions, then enable only WarpScript one...
VScode 1.47
WarpScript extension 1.1.24

**Comment by vballu** [comment]
I am on fedora 32.

Indeed, disabling all the other extension fix the issue. I try to figure out which on being a problem and I'll tell you

**Comment by vballu** [comment]
Okay, I think that the guilty is it https://github.com/tuttieee/vscode-emacs-mcx.
So, I will remove it.
Thank you for your answers

**Comment by Giwi** [comment]
You're welcome :)
