### ISSUE TITLE
String that contain single '\' at end destroys syntax higlightning 

### ISSUE THREAD

**Issue by dermoritz** [senx/VSCode-WarpScriptLanguage#49]
To split for example windows path something like 
... '\' SPLIT is needed

While running this code works as expected, the VSCode plugin completely fails with syntax higlighting:

good with double \:
![grafik](https://github.com/senx/VSCode-WarpScriptLanguage/assets/1814196/877b72df-6598-42d2-a13d-6935ce0f8d5c)

with only one \:
![grafik](https://github.com/senx/VSCode-WarpScriptLanguage/assets/1814196/9292e3c4-5342-40ff-bfbb-9df0652c6476)

within a macro it looks like this:

![grafik](https://github.com/senx/VSCode-WarpScriptLanguage/assets/1814196/1d269392-c284-4690-a248-ffad86769c76)

'\' seems to have a special meaning within plugin - but it should not have. please fix.

**Comment by pi-r-p** [comment]
It should be fixed in v2.4.5
